dist: bionic
language: java
jdk:
  - oraclejdk11
language: python
python:
  - "3.6"  
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - pip install Cython
  - pip install pyjnius
  - pip install PyYAML
install: true
script:
  - mvn clean package appassembler:assemble
  - find target/appassembler/bin/ -type f -exec sed -i 's/-Xmx.*G/-Xmx2G/g' {} \;
  - cd eval && tar xvfz trec_eval.9.0.4.tar.gz && cd trec_eval.9.0.4 && make && cd .. && cd ..
  - python src/main/python/run_regression.py --collection cacm --index --fail_eval
after_success:
  - bash <(curl -s https://codecov.io/bash)
