language: java
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - pip install --user pip --upgrade pip
  - pip install --user cython --upgrade Cython
  - pip install --user pyjnius --upgrade pyjnius
install: true
jdk:
  - oraclejdk8
script:
  - mvn clean package appassembler:assemble
  - git clone https://github.com/castorini/Anserini-data.git
  - python src/main/python/run_regression.py --config src/main/resources/regression/cacm.yaml --collection cacm --index --fail_eval
  - ls target | grep fatjar | xargs python src/test/python/python_interface.py

